"""
Catamount Community Bank - Dictionary Attack

A program to hash and compare words from a list of common word to the hashes
generated by unknown password. If a match is found, program will output the
username and password for the match.

Sources: https://docs.python.org/3/library/hashlib.html
         https://www.geeksforgeeks.org/sha-in-python/
         https://docs.python.org/3/library/csv.html
         https://www.geeksforgeeks.org/how-to-read-from-a-file-in-python/
"""

import sys
import hashlib
import csv

if __name__ == "__main__":

    hashed_words = {}

    #add the hashed version of common words to a dictionary
    try:
        with open("./words_to_test.txt", "r") as words:
            for word in words:
                #get rid of newline characters
                currWord = word.strip()
                hashed_words[currWord] = hashlib.sha1(currWord.encode()).hexdigest()
        words.close()
    except FileNotFoundError:
        print("Error opening words_to_test file")
        sys.exit()

    # open password hash file
    try:
        with open('./instance/static/passwd', 'r') as users:
            user_reader = csv.reader(users)
            # skip header
            next(user_reader)
            for row in user_reader:
                username = row[0]
                password_hash = row[2]
                # check each hash in the dictionary of common words to see if it matches a hash in the password file
                for word in hashed_words:
                    if password_hash.strip() == hashed_words[word].strip():
                        # print the username and password of any matches found
                        print(f"Username: {username} | Password: {word}")
        users.close()
    except FileNotFoundError:
        print("error opening password file")
        sys.exit()